version : "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ans123

  mongo-express:
    image : mongo-express
    ports:
      - 8081:8081
    environment :
      ME_CONFIG_MONGODB_ADMINUSER: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ans123
      ME_CONFIG_MONGODB_URL : mongodb://admin:ans123@mongo:27017/

